tasks:
  - func: "./producer.so"
    nprocs: 1
    args: ["--infile", "/home/tpeterka/software/spack/var/spack/environments/moab-workflow-env/moab-workflow/sample_data/mpas_2d_source_p128.h5m"]
    outports:
      - filename: "*.h5m"
        dsets:
          - name: "/*"
            passthru: 1
            metadata: 0
  - func: "./consumer.so"
    nprocs: 1
    args: ["{filename}"]
    inports:
      - filename: "*.h5m"
        dsets:
          - name: "/*"
            passthru: 1
            metadata: 0

