tasks:
  - func: "./producer.so"
    nprocs: 1
    args: []
    outports:
      - filename: "*.h5m"
        dsets:
          - name: "/*"
            passthru: 1
            metadata: 0
  - func: "./consumer.so"
    nprocs: 1
    args: ["{filename}"]
    inports:
      - filename: "*.h5m"
        dsets:
          - name: "/*"
            passthru: 1
            metadata: 0

