tasks:
  - func: "/home/tpeterka/software/mpas-o-workflow/install/bin/producer.so"
    nprocs: 1
    args: []
    outports:
      - filename: "*.h5m"
        dsets:
          - name: *
            passthru: 1
            metadata: 0
  - func: "/home/tpeterka/climate/mpas-o-workflow/install/bin/consumer.so"
    nprocs: 1
    args: ["{filename}"]
    inports:
      - filename: "*.h5m"
        dsets:
          - name: *
            passthru: 1
            metadata: 0

