tasks:
  - func: "/home/tpeterka/climate/E3SM/components/mpas-ocean/ocean_model.so"
    nprocs: 4
    args: ["-n", "namelist.ocean", "-s", "streams.ocean"]
    outports:
      - filename: "output.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
  - func: "./consumer.so"
    nprocs: 1
    args: ["-f", "output.nc"]
    inports:
      - filename: "output.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0

